version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app/uploads:/app/app/uploads
      - ./event_voting.db:/app/event_voting.db
    env_file:
      - .env
    restart: unless-stopped
